--
-- File generated with SQLiteStudio v3.1.0 on sáb jul 23 17:23:53 2016
--
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: Category
DROP TABLE IF EXISTS Category;
CREATE TABLE Category (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name STRING NOT NULL UNIQUE);

-- Table: Entry
DROP TABLE IF EXISTS Entry;
CREATE TABLE Entry (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, entry STRING NOT NULL, meaning STRING NOT NULL, source STRING, audio STRING, phonectic STRING);

-- Table: EntryCategory
DROP TABLE IF EXISTS EntryCategory;
CREATE TABLE EntryCategory (entry INTEGER REFERENCES Entry (id) ON DELETE CASCADE ON UPDATE CASCADE, category INTEGER REFERENCES Category (id) ON DELETE CASCADE ON UPDATE CASCADE, id INTEGER PRIMARY KEY AUTOINCREMENT);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
